/* JARVIS Core 2 — TEST HUD 72 LED + voice controls. */
class JarvisCoreHud extends HTMLElement {
  set hass(value) { this._hass = value; this._status?.classList.toggle("online", !!value); }
  connectedCallback() { this._render(); }
  _render() {
    const root = this.attachShadow({mode:"open"});
    const leds = Array.from({length:72},(_,i)=>{const a=i*5,r=i%2?47:43,x=50+r*Math.cos((a-90)*Math.PI/180),y=50+r*Math.sin((a-90)*Math.PI/180);return `<i class="led" style="left:${x}%;top:${y}%;transform:translate(-50%,-50%) rotate(${a}deg);animation-delay:${i*.035}s"></i>`}).join("");
    root.innerHTML=`<style>
:host{display:block;height:100%;min-height:78vh;background:#01050c;color:#d9faff;font-family:Arial,sans-serif}*{box-sizing:border-box}.hud{min-height:78vh;height:100%;display:flex;flex-direction:column;align-items:center;background:radial-gradient(circle at 50% 43%,rgba(0,180,255,.14),transparent 45%),#01050c;overflow:hidden}.title{margin:18px 0 0;font-size:clamp(28px,6vw,48px);letter-spacing:12px;text-shadow:0 0 12px #00eaff}.sub{font-size:10px;letter-spacing:4px;opacity:.7}.status{margin:8px;padding:5px 12px;border:1px solid #078;border-radius:20px;font-size:10px;letter-spacing:2px;color:#00eaff}.status.online{color:#39ff88;border-color:#294}.coreZone{position:relative;width:min(88vw,650px);aspect-ratio:1;display:grid;place-items:center}.ring{position:absolute;border:1px solid rgba(0,234,255,.28);border-radius:50%;box-shadow:0 0 18px rgba(0,234,255,.08)}.r1{width:34%;height:34%;animation:s 10s linear infinite}.r2{width:47%;height:47%;animation:r 15s linear infinite}.r3{width:61%;height:61%;animation:s 21s linear infinite}.r4{width:76%;height:76%;animation:r 28s linear infinite}.r5{width:91%;height:91%;animation:s 38s linear infinite}.ring:after{content:"";position:absolute;left:50%;top:-3px;width:7px;height:7px;border-radius:50%;background:#00eaff;box-shadow:0 0 12px #00eaff}.led{position:absolute;width:3px;height:14px;border-radius:3px;background:#00eaff;box-shadow:0 0 7px #00eaff;animation:p 1.9s ease-in-out infinite}.core{width:25%;height:25%;border-radius:50%;background:radial-gradient(circle,#031b29 0 20%,rgba(0,234,255,.22),transparent 70%);box-shadow:0 0 30px rgba(0,234,255,.4);display:grid;place-items:center;font-size:42px;font-weight:900;text-shadow:0 0 15px #00eaff}.core:after{content:"J"}.controls{display:flex;gap:10px;z-index:5}.controls button{border:1px solid rgba(0,234,255,.5);background:rgba(0,20,35,.7);color:#d9faff;border-radius:18px;padding:8px 16px;font-size:12px}.controls button.active{box-shadow:0 0 18px #00eaff}.footer{font-size:9px;letter-spacing:3px;opacity:.5;margin:8px}@keyframes s{to{transform:rotate(360deg)}}@keyframes r{to{transform:rotate(-360deg)}}@keyframes p{0%,100%{opacity:.3}50%{opacity:1}}button{cursor:pointer}</style>
<main class="hud"><div class="title">JARVIS</div><div class="sub">CORE ASSISTANT · TEST</div><div id="status" class="status">PRÊT</div><section class="coreZone"><div class="ring r5"></div><div class="ring r4"></div><div class="ring r3"></div><div class="ring r2"></div><div class="ring r1"></div>${leds}<div class="core"></div></section><div class="controls"><button id="listen">🎙️ ÉCOUTER</button><button id="assist">▶ ASSIST</button></div><div class="footer">72 LED · VOICE TEST · CORE 2</div></main>`;
    this._status=root.querySelector("#status");
    root.querySelector("#listen").onclick=()=>this._listen();
    root.querySelector("#assist").onclick=()=>this._assist();
  }
  _set(t){if(this._status)this._status.textContent=t}
  _listen(){if(!("webkitSpeechRecognition" in window||"SpeechRecognition" in window)){this._set("VOIX NON DISPONIBLE DANS CE NAVIGATEUR");return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new R();r.lang="fr-FR";r.interimResults=false;this._set("ÉCOUTE…");r.onresult=e=>{const text=e.results[0][0].transcript;this._set(text);this._send(text)};r.onerror=()=>this._set("ERREUR MICRO");r.onend=()=>{};r.start()}
  _assist(){if(this._hass?.connection){this._set("ASSIST");this._hass.connection.sendMessagePromise({type:"assist_pipeline/run",start_stage:"stt",end_stage:"tts",pipeline_id:""}).catch(()=>this._set("ASSIST INDISPONIBLE"))}else this._set("HOME ASSISTANT NON CONNECTÉ")}
  _send(text){this._set("TRAITEMENT…");if(this._hass?.connection){this._hass.connection.sendMessagePromise({type:"assist_pipeline/run",start_stage:"stt",end_stage:"tts",input:text}).then(()=>this._set("RÉPONSE EN COURS")).catch(()=>this._set("ERREUR ASSIST"))}}
}
customElements.define("jarvis-core-hud",JarvisCoreHud);
